[package]
name = "depin-sdk-chain"
version = "0.1.0"
edition = "2021"
description = "Chain implementation components for the DePIN SDK"
license = "MIT OR Apache-2.0"

[dependencies]
depin-sdk-consensus = { path = "../consensus" }
depin-sdk-core = { path = "../core" }
depin-sdk-commitment-schemes = { path = "../commitment_schemes" }
depin-sdk-state-trees = { path = "../state_trees" }
depin-sdk-transaction-models = { path = "../transaction_models" }
depin-sdk-validator = { path = "../validator" }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

# Dependencies added for the mvsc binary, made optional
depin-sdk-crypto = { path = "../crypto", optional = true }
tokio = { workspace = true, features = ["full"], optional = true }
futures = { workspace = true, optional = true }
hex = { version = "0.4", optional = true }
clap = { version = "4.3", features = ["derive"], optional = true }
env_logger = { version = "0.10", optional = true }
libp2p = { version = "0.52", features = [
    "tokio",
    "gossipsub",
    "mdns",
    "macros",
    "tcp",
    "noise",
    "yamux",
], optional = true }


[features]
default = []
tendermint = []
custom-consensus = []
# Feature to enable building the binary and its dependencies
mvsc-bin = [
    "dep:depin-sdk-crypto",
    "dep:tokio",
    "dep:futures",
    "dep:hex",
    "dep:clap",
    "dep:env_logger",
    "dep:libp2p",
]

[[bin]]
name = "mvsc"
path = "src/bin/mvsc.rs"
required-features = ["mvsc-bin"]
