[package]
name = "ioi-test-utils"
version = "0.1.0"
edition = "2021"
description = "Utilities for testing the DePIN SDK components"
license = "MIT OR Apache-2.0"

[dependencies]
ioi-types = { path = "../types" }
rand = { workspace = true }
serde_json = { workspace = true }
