[package]
name = "ioi-test-utils"
version = "0.1.0"
edition = "2021"
description = "Utilities for testing the IOI SDK components"
license-file = "../../LICENSE-BBSL"
repository = "https://github.com/ioi-foundation/ioi-sdk"

[dependencies]
ioi-types = { path = "../types" }
rand = { workspace = true }
serde_json = { workspace = true }
