[package]
name = "depin-sdk-transaction-models"
version = "0.1.0"
edition = "2021"
description = "Transaction model implementations for the DePIN SDK"
license = "MIT OR Apache-2.0"

[dependencies]
depin-sdk-crypto = { path = "../crypto", optional = true }
depin-sdk-core = { path = "../core" }
log = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
anyhow = { workspace = true }


[features]
default = ["dep:depin-sdk-crypto"]
utxo-model = []
account-model = []
hybrid-model = []
