# Path: crates/transaction_models/Cargo.toml
[package]
name = "depin-sdk-transaction-models"
version = "0.1.0"
edition = "2021"
description = "Transaction model implementations for the DePIN SDK"
license = "MIT OR Apache-2.0"

[dependencies]
depin-sdk-api = { path = "../api" }
depin-sdk-types = { path = "../types" }
depin-sdk-services = { path = "../services", default-features = false }
depin-sdk-crypto = { path = "../crypto" }
depin-sdk-telemetry = { path = "../telemetry" }
dcrypt = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
async-trait = { workspace = true }
libp2p = { workspace = true }
bs58 = "0.4"
prost = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive", "std"] }
toml = { workspace = true }

[features]
default = []
# This feature enables the conditional compilation of the IBC dispatch logic
# within the transaction model, and it signals to the services crate
# that its 'svc-ibc' feature should also be enabled.
svc-ibc = ["depin-sdk-services/svc-ibc"]
