# Path: crates/vm/wasm/Cargo.toml
[package]
name = "ioi-vm-wasm"
version = "0.1.0"
edition = "2021"
description = "Wasmtime-based VM for the IOI SDK"
license-file = "../../../LICENSE-BBSL"
repository = "https://github.com/ioi-foundation/ioi-sdk"

[dependencies]
ioi-api = { path = "../../api" }
ioi-types = { path = "../../types" }
wasmtime = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
thiserror = { workspace = true }
