# Path: crates/node/Cargo.toml

[package]
name = "ioi-node"
version = "0.1.0"
edition = "2021"
description = "The primary validator node binary for the IOI SDK"
license = "MIT OR Apache-2.0"

[dependencies]
# Workspace Library Crates
ioi-api = { path = "../api" }
ioi-types = { path = "../types" }
ioi-execution = { path = "../execution" }
ioi-state = { path = "../state", default-features = false }
ioi-consensus = { path = "../consensus", default-features = false }
ioi-storage = { path = "../storage" }
ioi-networking = { path = "../networking" }
ioi-tx = { path = "../tx" }
ioi-validator = { path = "../validator", default-features = false }
ioi-crypto = { path = "../crypto" }
ioi-vm-wasm = { path = "../vm/wasm", optional = true }
ioi-services = { path = "../services" }
ioi-test-utils = { path = "../test_utils" }
ioi-client = { path = "../client" }
ioi-telemetry = { path = "../telemetry" }
http-rpc-gateway = { path = "../http-rpc-gateway" }
ibc-host = { path = "../ibc-host" }
ioi-ipc = { path = "../ipc" }
bincode = { workspace = true }
uuid = { version = "1.8.0", features = ["v4"] }
anyhow = { workspace = true }
clap = { workspace = true, features = [
    "derive",
    "cargo",
    "env",
], optional = true }
cfg-if = "1.0"
env_logger = { workspace = true, optional = true }
futures = { workspace = true }
hex = { workspace = true }
libp2p = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
rcgen = { workspace = true }
serde_json = { workspace = true }
bs58 = "0.4"
async-trait = { workspace = true }
toml = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_jcs = "0.1.0"

[features]
default = []

# This feature is for building the standard validator binaries.
validator-bins = [
    "dep:clap",
    "dep:env_logger",
    "ioi-validator/validator-bins",
    "ioi-consensus/round-robin",
    "dep:ioi-vm-wasm",
]

# This feature is for building the special malicious workload binary for testing.
malicious-bin = []

# State Tree features must propagate to BOTH commitment and validator crates

tree-iavl = ["ioi-state/tree-iavl", "ioi-validator/tree-iavl", "primitive-hash"]
tree-sparse-merkle = [
    "ioi-state/tree-sparse-merkle",
    "ioi-validator/tree-sparse-merkle",
    "primitive-hash",
]
tree-verkle = [
    "ioi-state/tree-verkle",
    "ioi-validator/tree-verkle",
    "primitive-kzg",
]
primitive-hash = ["ioi-state/primitive-hash", "ioi-validator/primitive-hash"]
primitive-kzg = ["ioi-state/primitive-kzg", "ioi-validator/primitive-kzg"]

# Consensus engine features
consensus-round-robin = [
    "ioi-validator/consensus-round-robin",
    "ioi-consensus/round-robin",
]
consensus-poa = ["ioi-validator/consensus-poa", "ioi-consensus/poa"]
consensus-pos = ["ioi-validator/consensus-pos", "ioi-consensus/pos"]

# VM Features
vm-wasm = ["dep:ioi-vm-wasm"]

# Service Features
ibc-deps = ["ioi-services/ibc-deps", "ioi-validator/ibc-deps"]

# Feature for building the malicious binary for testing
# This does not need to be propagated, as the test runner handles it.


[[bin]]
name = "orchestration"
path = "src/bin/orchestration.rs"
required-features = ["validator-bins"]

[[bin]]
name = "workload"
path = "src/bin/workload.rs"
required-features = ["validator-bins", "vm-wasm"]

[[bin]]
name = "guardian"
path = "src/bin/guardian.rs"
required-features = ["validator-bins"]

[[bin]]
name = "malicious-workload"
path = "src/bin/malicious-workload.rs"
required-features = ["malicious-bin", "validator-bins", "vm-wasm"]
