# Path: crates/node/Cargo.toml

[package]
name = "depin-sdk-node"
version = "0.1.0"
edition = "2021"
description = "The primary validator node binary for the DePIN SDK"
license = "MIT OR Apache-2.0"

[dependencies]
# Workspace Library Crates
depin-sdk-api = { path = "../api" }
depin-sdk-types = { path = "../types" }
depin-sdk-chain = { path = "../chain" }
depin-sdk-commitment = { path = "../commitment", default-features = false }
depin-sdk-consensus = { path = "../consensus", default-features = false }
depin-sdk-network = { path = "../network" }
depin-sdk-transaction-models = { path = "../transaction_models" }
depin-sdk-validator = { path = "../validator", default-features = false }
depin-sdk-crypto = { path = "../crypto" }
depin-sdk-vm-wasm = { path = "../vm/wasm", optional = true }
depin-sdk-services = { path = "../services" }
depin-sdk-test-utils = { path = "../test_utils" }
depin-sdk-client = { path = "../client" }

async-trait = { workspace = true }
# Workspace Dependencies (for binary)
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo", "env"] }
cfg-if = "1.0"
env_logger = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
libp2p = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
rcgen = { workspace = true }
serde_json = { workspace = true }
bs58 = "0.4"
toml = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_jcs = "0.1.0"

[features]
default = []

# This feature is for building the standard validator binaries.
validator-bins = ["depin-sdk-validator/validator-bins"]

# This feature is for building the special malicious workload binary for testing.
malicious-bin = []

# State Tree features must propagate to BOTH commitment and validator crates
tree-file = ["depin-sdk-commitment/tree-file", "depin-sdk-validator/tree-file"]
tree-hashmap = [
    "depin-sdk-commitment/tree-hashmap",
    "depin-sdk-validator/tree-hashmap",
]
tree-iavl = ["depin-sdk-commitment/tree-iavl", "depin-sdk-validator/tree-iavl"]
tree-sparse-merkle = [
    "depin-sdk-commitment/tree-sparse-merkle",
    "depin-sdk-validator/tree-sparse-merkle",
]
tree-verkle = [
    "depin-sdk-commitment/tree-verkle",
    "depin-sdk-validator/tree-verkle",
]
primitive-hash = [
    "depin-sdk-commitment/primitive-hash",
    "depin-sdk-validator/primitive-hash",
]
primitive-kzg = [
    "depin-sdk-commitment/primitive-kzg",
    "depin-sdk-validator/primitive-kzg",
]

# Consensus engine features
consensus-round-robin = [
    "depin-sdk-validator/consensus-round-robin",
    "depin-sdk-consensus/round-robin",
]
consensus-poa = ["depin-sdk-validator/consensus-poa", "depin-sdk-consensus/poa"]
consensus-pos = ["depin-sdk-validator/consensus-pos", "depin-sdk-consensus/pos"]

# VM Features
vm-wasm = ["dep:depin-sdk-vm-wasm"]

[[bin]]
name = "orchestration"
path = "src/bin/orchestration.rs"
required-features = ["validator-bins"]

[[bin]]
name = "workload"
path = "src/bin/workload.rs"
required-features = ["validator-bins", "vm-wasm"]

[[bin]]
name = "guardian"
path = "src/bin/guardian.rs"
required-features = ["validator-bins"]

[[bin]]
name = "malicious-workload"
path = "src/bin/malicious-workload.rs"
required-features = ["malicious-bin", "validator-bins", "vm-wasm"]
