# Path: crates/validator/Cargo.toml
[package]
name = "depin-sdk-validator"
version = "0.1.0"
edition = "2021"
description = "Validator container implementations for the DePIN SDK"
license = "MIT OR Apache-2.0"

[dependencies]
depin-sdk-api = { path = "../api" }
depin-sdk-types = { path = "../types" }
depin-sdk-consensus = { path = "../consensus", default-features = false }
depin-sdk-network = { path = "../network" }
depin-sdk-chain = { path = "../chain" }
depin-sdk-transaction-models = { path = "../transaction_models" }
depin-sdk-vm-wasm = { path = "../vm/wasm", optional = true }
depin-sdk-crypto = { path = "../crypto" }
log = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_jcs = "0.1.0"
tokio = { workspace = true, features = ["full", "sync"] }
axum = { workspace = true }
libp2p = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
toml = { workspace = true }
clap = { workspace = true, features = ["derive"], optional = true }
env_logger = { workspace = true, optional = true }
depin-sdk-commitment = { path = "../commitment", optional = true }
rand = { workspace = true }
hex = { workspace = true }

# Added for mTLS implementation
tokio-rustls = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
rcgen = { workspace = true }
webpki-roots = { workspace = true }

[features]
default = []
# This new feature will be used by Docker to build the node binary correctly.
validator-bins = [
    "dep:clap",
    "dep:env_logger",
    "dep:depin-sdk-commitment",
    "depin-sdk-consensus/round-robin",
    "dep:depin-sdk-vm-wasm",
]
consensus-round-robin = ["depin-sdk-consensus/round-robin"]
consensus-poa = ["depin-sdk-consensus/poa"]
consensus-pos = ["depin-sdk-consensus/pos"]

# VM Features
vm-wasm = ["dep:depin-sdk-vm-wasm"]

[[bin]]
name = "depin-sdk-node"
path = "src/bin/validator.rs"
required-features = ["validator-bins"]

[[bin]]
name = "validator_hybrid"
path = "src/bin/validator_hybrid.rs"
required-features = ["validator-bins"]
