# Path: crates/ipc_protocol/Cargo.toml
[package]
name = "ipc_protocol"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
